CREATE ROLE "aicam-admin" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:XD1oqSS5kLJ0/H6xEFd+Lw==$MQI/fqDQ3oMcbpa4X7248Mgdyw/x2osYD2cZ7Xr7/dM=:djrhMy9ze08XMrpPcjcrp9toZEE7BxNmMZmXCdVYpoE=';

CREATE DATABASE "aicam-db"
WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

GRANT TEMPORARY, CONNECT ON DATABASE "aicam-db" TO PUBLIC;

GRANT ALL ON DATABASE "aicam-db" TO "aicam-admin";

GRANT ALL ON DATABASE "aicam-db" TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT ALL ON TABLES TO "aicam-admin";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT EXECUTE ON FUNCTIONS TO "aicam-admin";

\connect aicam-db
CREATE SCHEMA IF NOT EXISTS aicam
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA aicam TO "aicam-admin";

GRANT ALL ON SCHEMA aicam TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA aicam
GRANT ALL ON TABLES TO "aicam-admin";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA aicam
GRANT ALL ON SEQUENCES TO "aicam-admin";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA aicam
GRANT EXECUTE ON FUNCTIONS TO "aicam-admin";

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA aicam
GRANT USAGE ON TYPES TO "aicam-admin";